export const BLOG_TITLE = [
  { title: "recommended column", sub_title: "オススメ", category: "" },
  { title: "recommended diet", sub_title: "ダイエット", category: "diet" },
  { title: "recommended beauty", sub_title: "美容", category: "beauty" },
  { title: "recommended healthy", sub_title: "健康", category: "healthy" },
];

export const BLOG_POSTS = [
  {
    id: 1,
    timestamp: 1621260300,
    title: "魚を食べて頭もカラダも元気に！",
    subtitle: "知っておきたい魚を食べるメリット",
    image: "/images/MyRecommend-1.jpg",
    tags: ["魚料理", "和食", "DHA"],
    category: "healthy",
  },
  {
    id: 2,
    timestamp: 1621260300,
    title: "魚を食べて頭もカラダも元気に！",
    subtitle: "知っておきたい魚を食べるメリット",
    image: "/images/MyRecommend-2.jpg",
    tags: ["魚料理", "和食", "DHA"],
    category: "healthy",
  },
  {
    id: 3,
    timestamp: 1621260300,
    title: "魚を食べて頭もカラダも元気に！",
    subtitle: "知っておきたい魚を食べるメリット",
    image: "/images/MyRecommend-3.jpg",
    tags: ["魚料理", "和食", "DHA"],
    category: "diet",
  },
  {
    id: 4,
    timestamp: 1621260300,
    title: "魚を食べて頭もカラダも元気に！",
    subtitle: "知っておきたい魚を食べるメリット",
    image: "/images/d01.jpg",
    tags: ["魚料理", "和食", "DHA"],
    category: "diet",
  },
  {
    id: 5,
    timestamp: 1621260300,
    title: "魚を食べて頭もカラダも元気に！",
    subtitle: "知っておきたい魚を食べるメリット",
    image: "/images/d02.jpg",
    tags: ["魚料理", "和食", "DHA"],
    category: "beauty",
  },
  {
    id: 6,
    timestamp: 1621260300,
    title: "魚を食べて頭もカラダも元気に！",
    subtitle: "知っておきたい魚を食べるメリット",
    image: "/images/l01.jpg",
    tags: ["魚料理", "和食", "DHA"],
    category: "diet",
  },
  {
    id: 7,
    timestamp: 1621260300,
    title: "魚を食べて頭もカラダも元気に！",
    subtitle: "知っておきたい魚を食べるメリット",
    image: "/images/l02.jpg",
    tags: ["魚料理", "和食", "DHA"],
    category: "healthy",
  },
  {
    id: 8,
    timestamp: 1621260300,
    title: "魚を食べて頭もカラダも元気に！",
    subtitle: "知っておきたい魚を食べるメリット",
    image: "/images/l03.jpg",
    tags: ["魚料理", "和食", "DHA"],
    category: "beauty",
  },
  {
    id: 9,
    timestamp: 1621346700,
    title: "毎日の運動習慣で健康的な体づくり",
    subtitle: "簡単にできる自宅トレーニング方法",
    image: "/images/m01.jpg",
    tags: ["運動", "トレーニング", "健康"],
    category: "diet",
  },
  {
    id: 10,
    timestamp: 1621433100,
    title: "美肌を作る食事術とは？",
    subtitle: "食べ物から始めるスキンケア対策",
    image: "/images/m02.jpg",
    tags: ["美容", "スキンケア", "食事"],
    category: "beauty",
  },
  {
    id: 11,
    timestamp: 1621519500,
    title: "質の良い睡眠をとるためのポイント",
    subtitle: "快適な睡眠で疲労回復",
    image: "/images/m03.jpg",
    tags: ["睡眠", "健康", "リラックス"],
    category: "healthy",
  },
  {
    id: 12,
    timestamp: 1621605900,
    title: "ビタミンCの効果的な摂取方法",
    subtitle: "美容と健康に欠かせない栄養素",
    image: "/images/column-1.jpg",
    tags: ["ビタミン", "栄養", "美容"],
    category: "beauty",
  },
  {
    id: 13,
    timestamp: 1621692300,
    title: "糖質制限の正しい知識",
    subtitle: "効果的なダイエット方法を解説",
    image: "/images/column-2.jpg",
    tags: ["ダイエット", "糖質制限", "食事"],
    category: "diet",
  },
  {
    id: 14,
    timestamp: 1621778700,
    title: "朝食の重要性について",
    subtitle: "1日を元気に過ごすための習慣",
    image: "/images/column-3.jpg",
    tags: ["朝食", "健康", "栄養"],
    category: "healthy",
  },
  {
    id: 15,
    timestamp: 1621865100,
    title: "ストレス解消法とリラックス方法",
    subtitle: "心と体の健康管理",
    image: "/images/column-4.jpg",
    tags: ["メンタルヘルス", "リラックス", "健康"],
    category: "healthy",
  },
  {
    id: 16,
    timestamp: 1621951500,
    title: "美容にいい飲み物の選び方",
    subtitle: "デトックスドリンクレシピ",
    image: "/images/column-5.jpg",
    tags: ["デトックス", "美容", "ドリンク"],
    category: "beauty",
  }
];
